In [1]:
import numpy as np
import pandas as pd

In [2]:
weather_hist = pd.read_csv('weatherHistory.csv')

In [3]:
weather_hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96450 entries, 0 to 96449
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Formatted Date            96450 non-null  object 
 1   Summary                   96450 non-null  object 
 2   Precip Type               95930 non-null  object 
 3   Temperature (C)           96450 non-null  float64
 4   Apparent Temperature (C)  96450 non-null  float64
 5   Humidity                  96450 non-null  float64
 6   Wind Speed (km/h)         96445 non-null  float64
 7   Wind Bearing (degrees)    96450 non-null  int64  
 8   Visibility (km)           96442 non-null  float64
 9   Loud Cover                96450 non-null  int64  
 10  Pressure (millibars)      96443 non-null  float64
 11  Daily Summary             96450 non-null  object 
dtypes: float64(6), int64(2), object(4)
memory usage: 8.8+ MB


In [4]:
weather_hist.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [5]:
weather_hist.describe()

Temperature (C)  Apparent Temperature (C)      Humidity  \
count     96450.000000              96450.000000  96450.000000   
mean         11.932456                 10.854838      0.734912   
std           9.551517                 10.696820      0.195462   
min         -21.822222                -27.716667      0.000000   
25%           4.688889                  2.311111      0.600000   
50%          12.000000                 12.000000      0.780000   
75%          18.838889                 18.838889      0.890000   
max          39.905556                 39.344444      1.000000   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
count       96445.000000            96450.000000     96442.000000     96450.0   
mean           10.809563              187.507838        10.347331         0.0   
std             6.910700              107.384208         4.192359         0.0   
min             0.000000                0.000000         0.000000         0.0   
25%             5.828200              116.000000         8.339800         0.0   
50%             9.965900              180.000000        10.046400         0.0   
75%            14.135800              290.000000        14.812000         0.0   
max            55.931400              359.000000        16.100000         0.0   

       Pressure (millibars)  
count          96443.000000  
mean            1003.235465  
std              116.975940  
min                0.000000  
25%             1011.900000  
50%             1016.450000  
75%             1021.090000  
max             1046.380000

In [6]:
print("Number of Columns in the Weather History Data frame:", weather_hist.shape[1])
print("Number of records in the Weather History data frame:", weather_hist.shape[0])

Number of Columns in the Weather History Data frame: 12
Number of records in the Weather History data frame: 96450


In [7]:
print ("Unique values are:\n",weather_hist.nunique())

Unique values are:
 Formatted Date              96426
Summary                        24
Precip Type                     4
Temperature (C)              7574
Apparent Temperature (C)     8984
Humidity                       90
Wind Speed (km/h)            2483
Wind Bearing (degrees)        360
Visibility (km)               949
Loud Cover                      1
Pressure (millibars)         4979
Daily Summary                 214
dtype: int64


In [8]:

duplicates = weather_hist[weather_hist.duplicated()]

# Print the number of duplicate rows, if any
num_duplicates = len(duplicates)
if num_duplicates > 0:
    print("\n")
    print(f"{num_duplicates} duplicate rows found in Weathe History Dataset.")
    print("\n")
    print(duplicates)
else:
    print("No duplicate rows found in WeatherHistory.")



24 duplicate rows found in Weathe History Dataset.


                      Formatted Date        Summary Precip Type  \
36071  2010-08-02 00:00:00.000 +0200          Clear        rain   
36072  2010-08-02 01:00:00.000 +0200          Clear        rain   
36073  2010-08-02 02:00:00.000 +0200          Clear        rain   
36074  2010-08-02 03:00:00.000 +0200          Clear        rain   
36075  2010-08-02 04:00:00.000 +0200          Clear        rain   
36076  2010-08-02 05:00:00.000 +0200          Clear        rain   
36077  2010-08-02 06:00:00.000 +0200          Clear        rain   
36078  2010-08-02 07:00:00.000 +0200          Clear        rain   
36079  2010-08-02 08:00:00.000 +0200          Clear        rain   
36080  2010-08-02 09:00:00.000 +0200          Clear        rain   
36081  2010-08-02 10:00:00.000 +0200          Clear        rain   
36082  2010-08-02 11:00:00.000 +0200          Clear        rain   
36083  2010-08-02 12:00:00.000 +0200          Clear        rain   
36084  

In [9]:
# Removing duplicated values
weather_hist.drop_duplicates(inplace=True)
# Again checking for duplicated values
print("Duplicated Values: ", weather_hist.duplicated().sum())

Duplicated Values:  0


In [10]:
#Printing the shape of dataset after deleting Duplicates
print("Number of Columns in the Weather History Data frame:", weather_hist.shape[1])
print("Number of records in the Weather History data frame:", weather_hist.shape[0])

Number of Columns in the Weather History Data frame: 12
Number of records in the Weather History data frame: 96426


In [11]:
# Checking missing values

# Check for null values in the DataFrame
null_values = weather_hist.isnull().sum()

# Print the count of null values in each column
print('Checking the NULL Values in  WeatherHistory Dataset..\n')

# Check if there are any null values
if null_values.sum() == 0:
    print(f'\n There are no null values in the given dataset.')
else:
    columns_with_null_values = null_values[null_values > 0].index.tolist()
    # Loop over the columns with null values and print the count of null values for each column
    for column in columns_with_null_values:
        count = null_values[column]
        print(f"Column '{column}' has {count} null values.")

Checking the NULL Values in  WeatherHistory Dataset..

Column 'Precip Type' has 520 null values.
Column 'Wind Speed (km/h)' has 5 null values.
Column 'Visibility (km)' has 8 null values.
Column 'Pressure (millibars)' has 7 null values.


In [12]:
# Handling missing values
weather_hist['Precip Type'].value_counts()

rain    85191
snow    10712
?           2
%           1
Name: Precip Type, dtype: int64

In [13]:
# Remove rows with missing values in 'Precip Type' column
weather_hist = weather_hist[(weather_hist['Precip Type'] != '?') & (weather_hist['Precip Type'] != '%')]

# Verify the changes
weather_hist['Precip Type'].value_counts()


rain    85191
snow    10712
Name: Precip Type, dtype: int64

In [14]:
# Remove rows with null values in specified columns
weather_hist = weather_hist.dropna(subset=['Precip Type', 'Wind Speed (km/h)', 'Visibility (km)', 'Pressure (millibars)'])



In [15]:
# Re-check Handling Missing Values
missing_values = weather_hist.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64


In [16]:
#Printing the shape of dataset after deleting Duplicates
print("Number of Columns in the Weather History Data frame:", weather_hist.shape[1])
print("Number of records in the Weather History data frame:", weather_hist.shape[0])

Number of Columns in the Weather History Data frame: 12
Number of records in the Weather History data frame: 95883


In [17]:
# Remove the 'Daily Summary' column from the DataFrame
weather_hist = weather_hist.drop('Daily Summary', axis=1)


 
### Here are some reasons to justify deleting the 'Daily Summary' column from the entire dataset:

##### Irrelevance for Analysis: The 'Daily Summary' column contains textual descriptions of daily weather summaries. If your analysis focuses more on numerical weather data (such as temperature, humidity, etc.) rather than descriptive summaries, keeping this column may not add value to your analysis.

##### Reduced Memory Usage: Textual data can occupy more memory compared to numerical data. By removing the 'Daily Summary' column, you can reduce the overall memory usage of your dataset, which can be beneficial for large datasets or when working with memory-constrained environments.

##### Simplicity and Focus: Removing irrelevant columns can simplify your dataset and focus your analysis on the key variables of interest. This can make your analysis more manageable and easier to interpret.

##### Enhanced Performance: With fewer columns, operations on the dataset, such as calculations or transformations, may be faster and more efficient, leading to improved performance in data processing tasks.

##### Consistency and Standardization: By removing a column that contains descriptive text, you can ensure that your dataset remains consistent in terms of data types (e.g., numeric data) and standardizes the format for easier processing and analysis.

In [18]:
# Define a dictionary mapping current weather summaries to new categories
weather_mapping = {
   'Clear': 'Clear Skies',
    'Partly Cloudy': 'Cloudy Skies',
    'Mostly Cloudy': 'Cloudy Skies',
    'Overcast': 'Cloudy Skies',
    'Foggy': 'Foggy Day',
    'Breezy and Foggy': 'Foggy Day',
    'Windy and Foggy': 'Foggy Day',
    'Breezy': 'Breezy Day',
    'Breezy and Mostly Cloudy': 'Breezy Day',
    'Breezy and Partly Cloudy': 'Breezy Day',
    'Breezy and Overcast': 'Breezy Day',
    'Windy': 'Windy Day',
    'Windy and Mostly Cloudy': 'Windy Day',
    'Windy and Partly Cloudy': 'Windy Day',
    'Windy and Overcast': 'Windy Day',
    'Humid and Mostly Cloudy': 'Humid Day',
    'Humid and Partly Cloudy': 'Humid Day',
    'Humid and Overcast': 'Humid Day',
    'Dry': 'Dry Day',
    'Dry and Mostly Cloudy': 'Dry Day',
    'Dry and Partly Cloudy': 'Dry Day',
    'Light Rain': 'Rainy Day',
    'Drizzle': 'Rainy Day',
    'Rain': 'Rainy Day'
}

# Create a new column 'Weather Category' based on the mapping
weather_hist['Summary'] = weather_hist['Summary'].map(weather_mapping)

# Display the value counts of the new column
print(weather_hist['Summary'].value_counts())


Cloudy Skies    76035
Clear Skies     10744
Foggy Day        7155
Breezy Day       1484
Windy Day         155
Dry Day           134
Rainy Day         112
Humid Day          64
Name: Summary, dtype: int64


In [19]:
# Verify the changes
weather_hist.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 95883 entries, 0 to 96449
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Formatted Date            95883 non-null  object 
 1   Summary                   95883 non-null  object 
 2   Precip Type               95883 non-null  object 
 3   Temperature (C)           95883 non-null  float64
 4   Apparent Temperature (C)  95883 non-null  float64
 5   Humidity                  95883 non-null  float64
 6   Wind Speed (km/h)         95883 non-null  float64
 7   Wind Bearing (degrees)    95883 non-null  int64  
 8   Visibility (km)           95883 non-null  float64
 9   Loud Cover                95883 non-null  int64  
 10  Pressure (millibars)      95883 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 8.8+ MB


In [20]:
from datetime import datetime

# Define the format string for the date
format_string = "%Y-%m-%d %H:%M:%S.%f %z"

# Function to check if a value is in the correct format
def check_date_format(value):
    try:
        datetime.strptime(value, format_string)
        return True
    except ValueError:
        return False

# Apply the function to each value in the 'Formatted Date' column and create a new column 'is_valid_date'
weather_hist['is_valid_date'] = weather_hist['Formatted Date'].apply(check_date_format)

# Filter the DataFrame to show only rows where 'is_valid_date' is False
invalid_dates = weather_hist[~weather_hist['is_valid_date']]

# Display the rows with invalid dates
print("Rows with invalid dates:")
print(invalid_dates[['Formatted Date', 'is_valid_date']])


Rows with invalid dates:
Empty DataFrame
Columns: [Formatted Date, is_valid_date]
Index: []


In [21]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Label encode object columns
object_columns = ['Summary', 'Precip Type']
for col in object_columns:
    weather_hist[col+'_encoded'] = label_encoder.fit_transform(weather_hist[col])

# Convert 'Formatted Date' to datetime format with utc=True
weather_hist['Formatted Date'] = pd.to_datetime(weather_hist['Formatted Date'], utc=True)

# Extract year, month, day, and hour
weather_hist['Year'] = weather_hist['Formatted Date'].dt.year
weather_hist['Month'] = weather_hist['Formatted Date'].dt.month
weather_hist['Day'] = weather_hist['Formatted Date'].dt.day
weather_hist['Hour'] = weather_hist['Formatted Date'].dt.hour

# Create dictionaries for mapping encoded values to original labels
summary_mapping = dict(zip(weather_hist['Summary_encoded'], weather_hist['Summary']))
precip_mapping = dict(zip(weather_hist['Precip Type_encoded'], weather_hist['Precip Type']))

# Display the updated DataFrame and the mapping dictionaries
print("Weather History DataFrame:")
weather_hist[['Summary', 'Precip Type', 'Summary_encoded', 'Precip Type_encoded', 'Year', 'Month', 'Day', 'Hour']].head()



Weather History DataFrame:


Summary Precip Type  Summary_encoded  Precip Type_encoded  Year  \
0  Cloudy Skies        rain                2                    0  2006   
1  Cloudy Skies        rain                2                    0  2006   
2  Cloudy Skies        rain                2                    0  2006   
3  Cloudy Skies        rain                2                    0  2006   
4  Cloudy Skies        rain                2                    0  2006   

   Month  Day  Hour  
0      3   31    22  
1      3   31    23  
2      4    1     0  
3      4    1     1  
4      4    1     2

In [22]:
weather_hist

Formatted Date       Summary Precip Type  Temperature (C)  \
0     2006-03-31 22:00:00+00:00  Cloudy Skies        rain         9.472222   
1     2006-03-31 23:00:00+00:00  Cloudy Skies        rain         9.355556   
2     2006-04-01 00:00:00+00:00  Cloudy Skies        rain         9.377778   
3     2006-04-01 01:00:00+00:00  Cloudy Skies        rain         8.288889   
4     2006-04-01 02:00:00+00:00  Cloudy Skies        rain         8.755556   
...                         ...           ...         ...              ...   
96445 2016-09-09 17:00:00+00:00  Cloudy Skies        rain        26.016667   
96446 2016-09-09 18:00:00+00:00  Cloudy Skies        rain        24.583333   
96447 2016-09-09 19:00:00+00:00  Cloudy Skies        rain        22.038889   
96448 2016-09-09 20:00:00+00:00  Cloudy Skies        rain        21.522222   
96449 2016-09-09 21:00:00+00:00  Cloudy Skies        rain        20.438889   

       Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                      7.388889      0.89            14.1197   
1                      7.227778      0.86            14.2646   
2                      9.377778      0.89             3.9284   
3                      5.944444      0.83            14.1036   
4                      6.977778      0.83            11.0446   
...                         ...       ...                ...   
96445                 26.016667      0.43            10.9963   
96446                 24.583333      0.48            10.0947   
96447                 22.038889      0.56             8.9838   
96448                 21.522222      0.60            10.5294   
96449                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                         251          15.8263           0   
1                         259          15.8263           0   
2                         204          14.9569           0   
3                         269          15.8263           0   
4                         259          15.8263           0   
...                       ...              ...         ...   
96445                      31          16.1000           0   
96446                      20          15.5526           0   
96447                      30          16.1000           0   
96448                      20          16.1000           0   
96449                      39          15.5204           0   

       Pressure (millibars)  is_valid_date  Summary_encoded  \
0                   1015.13           True                2   
1                   1015.63           True                2   
2                   1015.94           True                2   
3                   1016.41           True                2   
4                   1016.51           True                2   
...                     ...            ...              ...   
96445               1014.36           True                2   
96446               1015.16           True                2   
96447               1015.66           True                2   
96448               1015.95           True                2   
96449               1016.16           True                2   

       Precip Type_encoded  Year  Month  Day  Hour  
0                        0  2006      3   31    22  
1                        0  2006      3   31    23  
2                        0  2006      4    1     0  
3                        0  2006      4    1     1  
4                        0  2006      4    1     2  
...                    ...   ...    ...  ...   ...  
96445                    0  2016      9    9    17  
96446                    0  2016      9    9    18  
96447                    0  2016      9    9    19  
96448                    0  2016      9    9    20  
96449                    0  2016      9    9    21  

[95883 rows x 18 columns]

In [23]:
print("\nSummary Mapping:")

summary_mapping


Summary Mapping:


{2: 'Cloudy Skies',
 4: 'Foggy Day',
 0: 'Breezy Day',
 1: 'Clear Skies',
 5: 'Humid Day',
 7: 'Windy Day',
 3: 'Dry Day',
 6: 'Rainy Day'}

In [24]:
weather_hist['Summary'].value_counts()

Cloudy Skies    76035
Clear Skies     10744
Foggy Day        7155
Breezy Day       1484
Windy Day         155
Dry Day           134
Rainy Day         112
Humid Day          64
Name: Summary, dtype: int64

In [25]:
print("\nPrecip Type Mapping:")


precip_mapping


Precip Type Mapping:


{0: 'rain', 1: 'snow'}

In [26]:
# Assuming 'weather_hist' is your DataFrame

# Use factorize to encode 'Summary' and 'Precip Type' columns
weather_hist['Summary_encoded'], summary_mapping_index = weather_hist['Summary'].factorize()
weather_hist['Precip Type_encoded'], precip_mapping_index = weather_hist['Precip Type'].factorize()

# Display the mapping indexes
print("Summary Mapping Index:")
print(summary_mapping_index)

print("\nPrecip Type Mapping Index:")
print(precip_mapping_index)


Summary Mapping Index:
Index(['Cloudy Skies', 'Foggy Day', 'Breezy Day', 'Clear Skies', 'Humid Day',
       'Windy Day', 'Dry Day', 'Rainy Day'],
      dtype='object')

Precip Type Mapping Index:
Index(['rain', 'snow'], dtype='object')


In [27]:
# Assuming df is your DataFrame

# Get the unique values in the 'Summary' column before encoding
summary_unique_values = weather_hist['Summary'].unique()

# Get the unique values in the 'Precip Type' column before encoding
precip_unique_values = weather_hist['Precip Type'].unique()

# Display the unique values
print("Unique values in 'Summary' column before encoding:")
print(summary_unique_values)

print("\nUnique values in 'Precip Type' column before encoding:")
print(precip_unique_values)


Unique values in 'Summary' column before encoding:
['Cloudy Skies' 'Foggy Day' 'Breezy Day' 'Clear Skies' 'Humid Day'
 'Windy Day' 'Dry Day' 'Rainy Day']

Unique values in 'Precip Type' column before encoding:
['rain' 'snow']


In [28]:
# Drop original categorical columns
weather_hist = weather_hist.drop(columns=['Summary', 'Precip Type', 'Formatted Date'])

# Display the updated DataFrame
print("Encoded Weather History DataFrame:")
weather_hist.head()


Encoded Weather History DataFrame:


Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0         9.472222                  7.388889      0.89            14.1197   
1         9.355556                  7.227778      0.86            14.2646   
2         9.377778                  9.377778      0.89             3.9284   
3         8.288889                  5.944444      0.83            14.1036   
4         8.755556                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

   is_valid_date  Summary_encoded  Precip Type_encoded  Year  Month  Day  Hour  
0           True                0                    0  2006      3   31    22  
1           True                0                    0  2006      3   31    23  
2           True                0                    0  2006      4    1     0  
3           True                0                    0  2006      4    1     1  
4           True                0                    0  2006      4    1     2

In [29]:
weather_hist['is_valid_date'].value_counts().get(False, 0)


0

In [30]:
weather_hist.shape

(95883, 15)

In [31]:
# Assuming df is your DataFrame
columns_to_remove = ['is_valid_date']
weather_hist = weather_hist.drop(columns=columns_to_remove)

# Display the updated DataFrame
weather_hist.head()


Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0         9.472222                  7.388889      0.89            14.1197   
1         9.355556                  7.227778      0.86            14.2646   
2         9.377778                  9.377778      0.89             3.9284   
3         8.288889                  5.944444      0.83            14.1036   
4         8.755556                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

   Summary_encoded  Precip Type_encoded  Year  Month  Day  Hour  
0                0                    0  2006      3   31    22  
1                0                    0  2006      3   31    23  
2                0                    0  2006      4    1     0  
3                0                    0  2006      4    1     1  
4                0                    0  2006      4    1     2

In [32]:
# Rename the columns
weather_hist = weather_hist.rename(columns={'Summary_encoded': 'Summary', 'Precip Type_encoded': 'Precip Type'})

# Display the updated DataFrame
print("Updated Weather History DataFrame:")
weather_hist.head()


Updated Weather History DataFrame:


Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0         9.472222                  7.388889      0.89            14.1197   
1         9.355556                  7.227778      0.86            14.2646   
2         9.377778                  9.377778      0.89             3.9284   
3         8.288889                  5.944444      0.83            14.1036   
4         8.755556                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                     251          15.8263           0               1015.13   
1                     259          15.8263           0               1015.63   
2                     204          14.9569           0               1015.94   
3                     269          15.8263           0               1016.41   
4                     259          15.8263           0               1016.51   

   Summary  Precip Type  Year  Month  Day  Hour  
0        0            0  2006      3   31    22  
1        0            0  2006      3   31    23  
2        0            0  2006      4    1     0  
3        0            0  2006      4    1     1  
4        0            0  2006      4    1     2

In [33]:
weather_hist.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95883 entries, 0 to 96449
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Temperature (C)           95883 non-null  float64
 1   Apparent Temperature (C)  95883 non-null  float64
 2   Humidity                  95883 non-null  float64
 3   Wind Speed (km/h)         95883 non-null  float64
 4   Wind Bearing (degrees)    95883 non-null  int64  
 5   Visibility (km)           95883 non-null  float64
 6   Loud Cover                95883 non-null  int64  
 7   Pressure (millibars)      95883 non-null  float64
 8   Summary                   95883 non-null  int64  
 9   Precip Type               95883 non-null  int64  
 10  Year                      95883 non-null  int64  
 11  Month                     95883 non-null  int64  
 12  Day                       95883 non-null  int64  
 13  Hour                      95883 non-null  int64  
dtypes: flo

In [34]:
missing_values = weather_hist.isnull().sum()
print("Missing values:")
missing_values


Missing values:


Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Summary                     0
Precip Type                 0
Year                        0
Month                       0
Day                         0
Hour                        0
dtype: int64

In [35]:
duplicate_rows = weather_hist[weather_hist.duplicated()]
print("\nDuplicate rows:")
duplicate_rows



Duplicate rows:


Empty DataFrame
Columns: [Temperature (C), Apparent Temperature (C), Humidity, Wind Speed (km/h), Wind Bearing (degrees), Visibility (km), Loud Cover, Pressure (millibars), Summary, Precip Type, Year, Month, Day, Hour]
Index: []

In [36]:
null_values = weather_hist.isna().sum()
print("\nNull values:")
null_values



Null values:


Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Summary                     0
Precip Type                 0
Year                        0
Month                       0
Day                         0
Hour                        0
dtype: int64

In [37]:
cl0 = weather_hist.query('Summary == 0 or Summary == 1 or Summary == 2')
cl1 = weather_hist.query('Summary == 3 or Summary == 4 or Summary == 5 or Summary == 6 or Summary == 7')

In [38]:
cl1['Summary'] = cl1['Summary'].map({3:0,4:1,5:2,6:3,7:4})

C:\Users\student\AppData\Local\Temp\ipykernel_9416\3072624506.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cl1['Summary'] = cl1['Summary'].map({3:0,4:1,5:2,6:3,7:4})


In [39]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
import optuna
from sklearn.model_selection import cross_val_score

# Split the dataset into features (X) and target variable (y)
X = cl0.drop(['Summary'], axis=1)
y = cl0['Summary']



# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


def objective(trial):
    param = {
        'objective': 'multi:softmax',
        'num_class': 3,
        'eval_metric': 'mlogloss',
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'verbosity': 0
    }

    model = XGBClassifier(**param)
    scores = cross_val_score(model, X, y, cv=5)
    accuracy = scores.mean()
    return accuracy

In [40]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2024-03-27 09:16:15,343] A new study created in memory with name: no-name-b0e8a451-a4c8-4b8c-aedd-a1fe130af4d7
[I 2024-03-27 09:16:20,620] Trial 0 finished with value: 0.9967994822742066 and parameters: {'eta': 0.2165322433517538, 'max_depth': 10, 'min_child_weight': 1, 'subsample': 0.6948199641157573, 'colsample_bytree': 0.654895410878194, 'gamma': 0.3003119135880353}. Best is trial 0 with value: 0.9967994822742066.
[I 2024-03-27 09:16:26,402] Trial 1 finished with value: 0.9969175808865479 and parameters: {'eta': 0.047578079342287825, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.7803996510322355, 'colsample_bytree': 0.6941674594756838, 'gamma': 0.466169021745784}. Best is trial 1 with value: 0.9969175808865479.
[I 2024-03-27 09:16:32,931] Trial 2 finished with value: 0.9968585329751878 and parameters: {'eta': 0.2934328162119524, 'max_depth': 3, 'min_child_weight': 10, 'subsample': 0.8377554633057493, 'colsample_bytree': 0.6713500446093876, 'gamma': 0.10135241591607158}. B

[I 2024-03-27 09:19:51,135] Trial 26 finished with value: 0.9969884442383844 and parameters: {'eta': 0.10489999548426537, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.7982941555815297, 'colsample_bytree': 0.9579187844055724, 'gamma': 0.24358606583073258}. Best is trial 13 with value: 0.9971537829930675.
[I 2024-03-27 09:19:57,898] Trial 27 finished with value: 0.9969648252133213 and parameters: {'eta': 0.19360959460222094, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.8908218673187859, 'colsample_bytree': 0.7870990145227945, 'gamma': 0.30008627545478456}. Best is trial 13 with value: 0.9971537829930675.
[I 2024-03-27 09:20:04,821] Trial 28 finished with value: 0.9968467210217378 and parameters: {'eta': 0.024726646767631144, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.9395839530292442, 'colsample_bytree': 0.8542649338883547, 'gamma': 0.0019609553315061423}. Best is trial 13 with value: 0.9971537829930675.
[I 2024-03-27 09:20:12,566] Trial 29 finished with valu

[I 2024-03-27 09:23:30,511] Trial 53 finished with value: 0.9970947308972757 and parameters: {'eta': 0.03510187644156696, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.5544277763687865, 'colsample_bytree': 0.9402738933653333, 'gamma': 0.07979725319603997}. Best is trial 49 with value: 0.9971892111819594.
[I 2024-03-27 09:23:40,217] Trial 54 finished with value: 0.9970474914523392 and parameters: {'eta': 0.04905033362791533, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.5786635307704036, 'colsample_bytree': 0.9976358929849237, 'gamma': 0.12153534751057744}. Best is trial 49 with value: 0.9971892111819594.
[I 2024-03-27 09:23:48,017] Trial 55 finished with value: 0.9969648203314844 and parameters: {'eta': 0.010180714805184857, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6580733143441545, 'colsample_bytree': 0.9533056138323105, 'gamma': 0.05550501370035629}. Best is trial 49 with value: 0.9971892111819594.
[I 2024-03-27 09:23:56,394] Trial 56 finished with value:

[I 2024-03-27 09:27:24,687] Trial 80 finished with value: 0.9968821506054404 and parameters: {'eta': 0.0331899552873234, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.6682862839580589, 'colsample_bytree': 0.8331035690825999, 'gamma': 0.09370000445072144}. Best is trial 72 with value: 0.9972128302070222.
[I 2024-03-27 09:27:34,167] Trial 81 finished with value: 0.997236453416517 and parameters: {'eta': 0.04843718547242603, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7241409464973516, 'colsample_bytree': 0.9998166840448134, 'gamma': 0.1183107954944656}. Best is trial 81 with value: 0.997236453416517.
[I 2024-03-27 09:27:44,181] Trial 82 finished with value: 0.9971537822956623 and parameters: {'eta': 0.04884782995589556, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.647680709282815, 'colsample_bytree': 0.9866601246330161, 'gamma': 0.11756628767766447}. Best is trial 81 with value: 0.997236453416517.
[I 2024-03-27 09:27:52,101] Trial 83 finished with value: 0.997

In [41]:
from sklearn.metrics import classification_report, confusion_matrix

# Use the best hyperparameters found by Optuna
best_params = study.best_params
model = XGBClassifier(**best_params)

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the training and test sets
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate accuracies
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Generate confusion matrices
train_conf_matrix = confusion_matrix(y_train, y_train_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Generate classification reports
train_classification_report = classification_report(y_train, y_train_pred)
test_classification_report = classification_report(y_test, y_test_pred)

# Print the results
print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

print("\nTrain Confusion Matrix:")
print(train_conf_matrix)

print("\nTest Confusion Matrix:")
print(test_conf_matrix)

print("\nTrain Classification Report:")
print(train_classification_report)

print("\nTest Classification Report:")
print(test_classification_report)


Train Accuracy: 0.9995423611213629
Test Accuracy: 0.9987009152642456

Train Confusion Matrix:
[[60809     0    13]
 [   16  5709     0]
 [    2     0  1190]]

Test Confusion Matrix:
[[15204     2     7]
 [   12  1418     0]
 [    1     0   291]]

Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     60822
           1       1.00      1.00      1.00      5725
           2       0.99      1.00      0.99      1192

    accuracy                           1.00     67739
   macro avg       1.00      1.00      1.00     67739
weighted avg       1.00      1.00      1.00     67739


Test Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     15213
           1       1.00      0.99      1.00      1430
           2       0.98      1.00      0.99       292

    accuracy                           1.00     16935
   macro avg       0.99      1.00      0.9

In [42]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
import optuna
from sklearn.model_selection import cross_val_score

# Split the dataset into features (X) and target variable (y)
X = cl1.drop(['Summary'], axis=1)
y = cl1['Summary']



# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


def objective(trial):
    param = {
        'objective': 'multi:softmax',
        'num_class': 5,
        'eval_metric': 'mlogloss',
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'verbosity': 0
    }

    model = XGBClassifier(**param)
    scores = cross_val_score(model, X, y, cv=5)
    accuracy = scores.mean()
    return accuracy

In [43]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2024-03-27 09:29:52,174] A new study created in memory with name: no-name-838bdf22-33fc-44e2-a788-7bd2c43a6ad8
[I 2024-03-27 09:29:56,213] Trial 0 finished with value: 0.9367306474385997 and parameters: {'eta': 0.01929487067910353, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7717161753408044, 'colsample_bytree': 0.91737116851507, 'gamma': 0.1125315159376421}. Best is trial 0 with value: 0.9367306474385997.
[I 2024-03-27 09:29:58,941] Trial 1 finished with value: 0.9609170749804651 and parameters: {'eta': 0.26994122761228306, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.9577668084551028, 'colsample_bytree': 0.9038715058141457, 'gamma': 0.09196750862492792}. Best is trial 1 with value: 0.9609170749804651.
[I 2024-03-27 09:30:02,438] Trial 2 finished with value: 0.9393185787057439 and parameters: {'eta': 0.034142602847795786, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9018294429755069, 'colsample_bytree': 0.6960637440242141, 'gamma': 0.10321122238298064}. 

[I 2024-03-27 09:31:03,660] Trial 26 finished with value: 0.9677004379894442 and parameters: {'eta': 0.0685151098682901, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.6979688718616598, 'colsample_bytree': 0.5215781248017967, 'gamma': 0.36458521240647546}. Best is trial 25 with value: 0.9745718924861901.
[I 2024-03-27 09:31:05,976] Trial 27 finished with value: 0.9725186801323641 and parameters: {'eta': 0.12888783210172886, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.8602620148055538, 'colsample_bytree': 0.6080251373642143, 'gamma': 0.012804701429873833}. Best is trial 25 with value: 0.9745718924861901.
[I 2024-03-27 09:31:08,584] Trial 28 finished with value: 0.9724296730981813 and parameters: {'eta': 0.13631921476941022, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.896649776756873, 'colsample_bytree': 0.6070091542836462, 'gamma': 0.04696324597572936}. Best is trial 25 with value: 0.9745718924861901.
[I 2024-03-27 09:31:12,181] Trial 29 finished with value: 0

[I 2024-03-27 09:32:18,043] Trial 53 finished with value: 0.9716269777295325 and parameters: {'eta': 0.07624949341115213, 'max_depth': 10, 'min_child_weight': 10, 'subsample': 0.8417492195058337, 'colsample_bytree': 0.5388200814389001, 'gamma': 0.06518833113830845}. Best is trial 41 with value: 0.9759103815400365.
[I 2024-03-27 09:32:20,768] Trial 54 finished with value: 0.97305439420483 and parameters: {'eta': 0.09319100107637618, 'max_depth': 9, 'min_child_weight': 9, 'subsample': 0.8119765892519549, 'colsample_bytree': 0.5616144215262859, 'gamma': 0.031667025872144504}. Best is trial 41 with value: 0.9759103815400365.
[I 2024-03-27 09:32:23,406] Trial 55 finished with value: 0.9737686398284188 and parameters: {'eta': 0.10944195308227747, 'max_depth': 10, 'min_child_weight': 10, 'subsample': 0.8347107412483714, 'colsample_bytree': 0.536234314480911, 'gamma': 0.0954448733799141}. Best is trial 41 with value: 0.9759103815400365.
[I 2024-03-27 09:32:26,041] Trial 56 finished with value:

[I 2024-03-27 09:33:30,415] Trial 80 finished with value: 0.9721620947065096 and parameters: {'eta': 0.08958170092486893, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.7798049909241838, 'colsample_bytree': 0.546141461730562, 'gamma': 0.03606340562905798}. Best is trial 41 with value: 0.9759103815400365.
[I 2024-03-27 09:33:33,054] Trial 81 finished with value: 0.9742150682221402 and parameters: {'eta': 0.09751284867552532, 'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.8026518898775047, 'colsample_bytree': 0.5289038667043675, 'gamma': 0.07745567373808522}. Best is trial 41 with value: 0.9759103815400365.
[I 2024-03-27 09:33:35,529] Trial 82 finished with value: 0.9751072881077286 and parameters: {'eta': 0.09847578219102934, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8057811255540525, 'colsample_bytree': 0.5298568899937546, 'gamma': 0.10804784791658811}. Best is trial 41 with value: 0.9759103815400365.
[I 2024-03-27 09:33:38,142] Trial 83 finished with value:

In [44]:
from sklearn.metrics import classification_report, confusion_matrix

# Use the best hyperparameters found by Optuna
best_params = study.best_params
model = XGBClassifier(**best_params)

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the training and test sets
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate accuracies
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Generate confusion matrices
train_conf_matrix = confusion_matrix(y_train, y_train_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Generate classification reports
train_classification_report = classification_report(y_train, y_train_pred)
test_classification_report = classification_report(y_test, y_test_pred)

# Print the results
print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

print("\nTrain Confusion Matrix:")
print(train_conf_matrix)

print("\nTest Confusion Matrix:")
print(test_conf_matrix)

print("\nTrain Classification Report:")
print(train_classification_report)

print("\nTest Classification Report:")
print(test_classification_report)


Train Accuracy: 0.9977695996431359
Test Accuracy: 0.9910793933987511

Train Confusion Matrix:
[[8597    0    1    2    1]
 [   1   51    0    0    0]
 [   0    1  127    0    0]
 [   9    0    0   93    0]
 [   5    0    0    0   79]]

Test Confusion Matrix:
[[2137    1    1    3    1]
 [   2   10    0    0    0]
 [   1    0   26    0    0]
 [  10    0    0   22    0]
 [   1    0    0    0   27]]

Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8601
           1       0.98      0.98      0.98        52
           2       0.99      0.99      0.99       128
           3       0.98      0.91      0.94       102
           4       0.99      0.94      0.96        84

    accuracy                           1.00      8967
   macro avg       0.99      0.96      0.98      8967
weighted avg       1.00      1.00      1.00      8967


Test Classification Report:
              precision    recall  f1-score   suppor

In [45]:
### Initial 2 classification models

fsCls = weather_hist
fsCls['Summary'] = fsCls['Summary'].map({0:0,1:0,2:0,3:1,4:1,5:1,6:1,7:1})

In [46]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
import optuna
from sklearn.model_selection import cross_val_score

# Split the dataset into features (X) and target variable (y)
X = fsCls.drop(['Summary'], axis=1)
y = fsCls['Summary']



# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


def objective(trial):
    param = {
        'objective': 'multi:softmax',
        'num_class': 2,
        'eval_metric': 'mlogloss',
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'verbosity': 0
    }

    model = XGBClassifier(**param)
    scores = cross_val_score(model, X, y, cv=5)
    accuracy = scores.mean()
    return accuracy

In [47]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2024-03-27 09:34:18,537] A new study created in memory with name: no-name-25a713cc-02ed-4328-adaa-9f99519ce7a7
[I 2024-03-27 09:34:28,536] Trial 0 finished with value: 0.5411736577171901 and parameters: {'eta': 0.24136590943742484, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.952884552478703, 'colsample_bytree': 0.6494874681429561, 'gamma': 0.36366793866400554}. Best is trial 0 with value: 0.5411736577171901.
[I 2024-03-27 09:34:34,319] Trial 1 finished with value: 0.6533005979754856 and parameters: {'eta': 0.1632683143014102, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.8342333242666085, 'colsample_bytree': 0.5917784370502893, 'gamma': 0.23167925045046805}. Best is trial 1 with value: 0.6533005979754856.
[I 2024-03-27 09:34:41,136] Trial 2 finished with value: 0.6673481744151475 and parameters: {'eta': 0.10213883635529455, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.5351475855690753, 'colsample_bytree': 0.7018227392346302, 'gamma': 0.2097139248980478}. B

[I 2024-03-27 09:38:21,600] Trial 26 finished with value: 0.6196230273110199 and parameters: {'eta': 0.0669604119895989, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7070306713449139, 'colsample_bytree': 0.5457255158157502, 'gamma': 0.060012410228401425}. Best is trial 17 with value: 0.7476535575781107.
[I 2024-03-27 09:38:28,130] Trial 27 finished with value: 0.6054707791102404 and parameters: {'eta': 0.12042149143880657, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.6329579750818555, 'colsample_bytree': 0.7231053102637682, 'gamma': 0.40550621008526966}. Best is trial 17 with value: 0.7476535575781107.
[I 2024-03-27 09:38:35,219] Trial 28 finished with value: 0.7120686808694248 and parameters: {'eta': 0.0333630136594972, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.813389835582454, 'colsample_bytree': 0.55997500353406, 'gamma': 0.3009610443587429}. Best is trial 17 with value: 0.7476535575781107.
[I 2024-03-27 09:38:46,348] Trial 29 finished with value: 0.564

[I 2024-03-27 09:42:08,652] Trial 53 finished with value: 0.7436279176167722 and parameters: {'eta': 0.05024190562189363, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9166615074756653, 'colsample_bytree': 0.556006015052952, 'gamma': 0.09687330037336286}. Best is trial 42 with value: 0.7534730772237088.
[I 2024-03-27 09:42:14,988] Trial 54 finished with value: 0.7520025591470314 and parameters: {'eta': 0.02554346173217246, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.9294549971008692, 'colsample_bytree': 0.5223726012440527, 'gamma': 0.139097022796411}. Best is trial 42 with value: 0.7534730772237088.
[I 2024-03-27 09:42:20,634] Trial 55 finished with value: 0.747538866187591 and parameters: {'eta': 0.040049211081756006, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9687831351909503, 'colsample_bytree': 0.6204259133605445, 'gamma': 0.10629334453129795}. Best is trial 42 with value: 0.7534730772237088.
[I 2024-03-27 09:42:27,297] Trial 56 finished with value: 0.7

[I 2024-03-27 09:46:09,127] Trial 80 finished with value: 0.7352009219864682 and parameters: {'eta': 0.036122103620546575, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.9871118891613849, 'colsample_bytree': 0.7511096511556841, 'gamma': 0.2915664094052961}. Best is trial 68 with value: 0.7544221672164165.
[I 2024-03-27 09:46:19,055] Trial 81 finished with value: 0.7542552897802131 and parameters: {'eta': 0.010831962992580884, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.9520550767782338, 'colsample_bytree': 0.8256750191402795, 'gamma': 0.2116890841265082}. Best is trial 68 with value: 0.7544221672164165.
[I 2024-03-27 09:46:30,277] Trial 82 finished with value: 0.7353466675385915 and parameters: {'eta': 0.017541352557463186, 'max_depth': 6, 'min_child_weight': 6, 'subsample': 0.9540525747381097, 'colsample_bytree': 0.8349947712843846, 'gamma': 0.2024936583909859}. Best is trial 68 with value: 0.7544221672164165.
[I 2024-03-27 09:46:40,878] Trial 83 finished with value: 

In [48]:
from sklearn.metrics import classification_report, confusion_matrix

# Use the best hyperparameters found by Optuna
best_params = study.best_params
model = XGBClassifier(**best_params)

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the training and test sets
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate accuracies
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Generate confusion matrices
train_conf_matrix = confusion_matrix(y_train, y_train_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Generate classification reports
train_classification_report = classification_report(y_train, y_train_pred)
test_classification_report = classification_report(y_test, y_test_pred)

# Print the results
print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

print("\nTrain Confusion Matrix:")
print(train_conf_matrix)

print("\nTest Confusion Matrix:")
print(test_conf_matrix)

print("\nTrain Classification Report:")
print(train_classification_report)

print("\nTest Classification Report:")
print(test_classification_report)


Train Accuracy: 0.884063828122963
Test Accuracy: 0.8866350315482088

Train Confusion Matrix:
[[67691     0]
 [ 8893   122]]

Test Confusion Matrix:
[[16982     1]
 [ 2173    21]]

Train Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     67691
           1       1.00      0.01      0.03      9015

    accuracy                           0.88     76706
   macro avg       0.94      0.51      0.48     76706
weighted avg       0.90      0.88      0.83     76706


Test Classification Report:
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     16983
           1       0.95      0.01      0.02      2194

    accuracy                           0.89     19177
   macro avg       0.92      0.50      0.48     19177
weighted avg       0.89      0.89      0.83     19177



In [49]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import pandas as pd

# Assuming weather_hist is your DataFrame containing the data
# Separate features and target variable
X = fsCls.drop(['Summary'], axis=1)
y = fsCls['Summary']

# Apply SMOTE
smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X, y)




In [50]:
X_train, X_test, y_train, y_test = train_test_split(X_smote, y_smote, test_size=0.2, random_state=42)


def objective(trial):
    param = {
        'objective': 'multi:softmax',
        'num_class': 2,
        'eval_metric': 'mlogloss',
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'verbosity': 0
    }

    model = XGBClassifier(**param)
    scores = cross_val_score(model, X, y, cv=5)
    accuracy = scores.mean()
    return accuracy

In [51]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2024-03-27 09:49:28,437] A new study created in memory with name: no-name-84f4ef5a-57c9-4af9-96ef-bb28cdb378a7
[I 2024-03-27 09:49:37,957] Trial 0 finished with value: 0.6459996541234589 and parameters: {'eta': 0.1481403765409055, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.823322378792247, 'colsample_bytree': 0.525362382353466, 'gamma': 0.3212619321622066}. Best is trial 0 with value: 0.6459996541234589.
[I 2024-03-27 09:49:53,374] Trial 1 finished with value: 0.5511129930298883 and parameters: {'eta': 0.2606824677226565, 'max_depth': 10, 'min_child_weight': 5, 'subsample': 0.7537220390399002, 'colsample_bytree': 0.6012593617437614, 'gamma': 0.04335536678776042}. Best is trial 0 with value: 0.6459996541234589.
[I 2024-03-27 09:50:10,531] Trial 2 finished with value: 0.5575267964037629 and parameters: {'eta': 0.19117834666843916, 'max_depth': 10, 'min_child_weight': 2, 'subsample': 0.7540752316434423, 'colsample_bytree': 0.7170861312468308, 'gamma': 0.13980095390147373}. 

[I 2024-03-27 09:54:19,956] Trial 26 finished with value: 0.5864889770806266 and parameters: {'eta': 0.08627299440736008, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.9493268581758423, 'colsample_bytree': 0.7084093097654155, 'gamma': 0.3414877990755836}. Best is trial 22 with value: 0.7540988572760327.
[I 2024-03-27 09:54:29,473] Trial 27 finished with value: 0.7139561167969323 and parameters: {'eta': 0.06184349540840654, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.861285745218535, 'colsample_bytree': 0.8810434293881791, 'gamma': 0.42551451555014863}. Best is trial 22 with value: 0.7540988572760327.
[I 2024-03-27 09:54:41,581] Trial 28 finished with value: 0.5472642816783393 and parameters: {'eta': 0.2979108010379325, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.9963967768244463, 'colsample_bytree': 0.8351467265204506, 'gamma': 0.02235615769259164}. Best is trial 22 with value: 0.7540988572760327.
[I 2024-03-27 09:54:51,866] Trial 29 finished with value: 0.5

[I 2024-03-27 09:58:06,391] Trial 53 finished with value: 0.7482271450583675 and parameters: {'eta': 0.022209984649099377, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.6299586942954754, 'colsample_bytree': 0.5858581906534988, 'gamma': 0.48382030389261993}. Best is trial 32 with value: 0.7545055868992347.
[I 2024-03-27 09:58:13,886] Trial 54 finished with value: 0.6792685323550547 and parameters: {'eta': 0.038255677535651546, 'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.6936719724193876, 'colsample_bytree': 0.6307399594633611, 'gamma': 0.4601234514527615}. Best is trial 32 with value: 0.7545055868992347.
[I 2024-03-27 09:58:19,625] Trial 55 finished with value: 0.7529829083385399 and parameters: {'eta': 0.02231218514811243, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.6012074354936919, 'colsample_bytree': 0.525467967029492, 'gamma': 0.43303151951275687}. Best is trial 32 with value: 0.7545055868992347.
[I 2024-03-27 09:58:25,794] Trial 56 finished with value: 

[I 2024-03-27 10:00:38,013] Trial 80 finished with value: 0.7544117266353153 and parameters: {'eta': 0.018653543210987764, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.9475687607212867, 'colsample_bytree': 0.8896866673733766, 'gamma': 0.38371700777823553}. Best is trial 32 with value: 0.7545055868992347.
[I 2024-03-27 10:00:43,760] Trial 81 finished with value: 0.754390866139992 and parameters: {'eta': 0.01803514358431843, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.9474118438190844, 'colsample_bytree': 0.8817625504271739, 'gamma': 0.3807708618844243}. Best is trial 32 with value: 0.7545055868992347.
[I 2024-03-27 10:00:49,481] Trial 82 finished with value: 0.751439357317486 and parameters: {'eta': 0.027440520163219087, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8947943909937671, 'colsample_bytree': 0.8815849731672784, 'gamma': 0.38458730677576747}. Best is trial 32 with value: 0.7545055868992347.
[I 2024-03-27 10:00:55,166] Trial 83 finished with value: 0

In [52]:
from sklearn.metrics import classification_report, confusion_matrix

# Use the best hyperparameters found by Optuna
best_params = study.best_params
model = XGBClassifier(**best_params)

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the training and test sets
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Calculate accuracies
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Generate confusion matrices
train_conf_matrix = confusion_matrix(y_train, y_train_pred)
test_conf_matrix = confusion_matrix(y_test, y_test_pred)

# Generate classification reports
train_classification_report = classification_report(y_train, y_train_pred)
test_classification_report = classification_report(y_test, y_test_pred)

# Print the results
print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

print("\nTrain Confusion Matrix:")
print(train_conf_matrix)

print("\nTest Confusion Matrix:")
print(test_conf_matrix)

print("\nTrain Classification Report:")
print(train_classification_report)

print("\nTest Classification Report:")
print(test_classification_report)


Train Accuracy: 0.7660210513884174
Test Accuracy: 0.7659285503395336

Train Confusion Matrix:
[[50866 16926]
 [14773 52913]]

Test Confusion Matrix:
[[12698  4184]
 [ 3744 13244]]

Train Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.75      0.76     67792
           1       0.76      0.78      0.77     67686

    accuracy                           0.77    135478
   macro avg       0.77      0.77      0.77    135478
weighted avg       0.77      0.77      0.77    135478


Test Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.75      0.76     16882
           1       0.76      0.78      0.77     16988

    accuracy                           0.77     33870
   macro avg       0.77      0.77      0.77     33870
weighted avg       0.77      0.77      0.77     33870

